# Generated by Django 5.2.14 on 2026-05-22 21:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lista de Materiales',
                'verbose_name_plural': 'Listas de Materiales',
                'ordering': ['project', 'material__name'],
            },
        ),
        migrations.CreateModel(
            name='BreakerCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('poles', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('ampacity', models.DecimalField(decimal_places=1, max_digits=6)),
                ('trip_curve', models.CharField(blank=True, choices=[('B', 'B — Baja retención (iluminación)'), ('C', 'C — Retención estándar (cargas generales)'), ('D', 'D — Alta retención (motores con alto arranque)'), ('K', 'K — Uso industrial'), ('Z', 'Z — Equipos electrónicos sensibles')], max_length=1)),
                ('ka_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Catálogo de Breakers',
                'verbose_name_plural': 'Catálogos de Breakers',
                'ordering': ['norm_version', 'poles', 'ampacity'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['project', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('circuit_number', models.PositiveSmallIntegerField()),
                ('length_meters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_three_phase', models.BooleanField(default=False)),
                ('phase_assignment', models.CharField(blank=True, choices=[('A', 'Fase A'), ('B', 'Fase B'), ('C', 'Fase C'), ('AB', 'Fase A-B (bifásico)'), ('BC', 'Fase B-C (bifásico)'), ('CA', 'Fase C-A (bifásico)'), ('ABC', 'Tres fases')], max_length=3)),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
                'ordering': ['panel', 'circuit_number'],
            },
        ),
        migrations.CreateModel(
            name='ConductorCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gauge_awg', models.CharField(max_length=10)),
                ('cross_section_mm2', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ampacity_30c', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
            options={
                'verbose_name': 'Catálogo de Conductores',
                'verbose_name_plural': 'Catálogos de Conductores',
                'ordering': ['norm_version', '-ampacity_30c'],
            },
        ),
        migrations.CreateModel(
            name='InsulationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('max_temperature_c', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Tipo de Aislamiento',
                'verbose_name_plural': 'Tipos de Aislamiento',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('default_power_factor', models.DecimalField(decimal_places=2, default=0.9, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('default_demand_factor', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'verbose_name': 'Tipo de Carga',
                'verbose_name_plural': 'Tipos de Carga',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialUnitMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Norma',
                'verbose_name_plural': 'Normas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PhaseConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active_conductors', models.PositiveSmallIntegerField()),
                ('has_neutral', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Fase',
                'verbose_name_plural': 'Configuraciones de Fase',
                'ordering': ['active_conductors', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('subdomain', models.CharField(max_length=63, unique=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WireMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('material_name', models.CharField(max_length=50, unique=True)),
                ('resistivity_ohm_mm2_m', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'verbose_name': 'Material Conductor',
                'verbose_name_plural': 'Materiales Conductores',
                'ordering': ['material_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['email'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.budget')),
            ],
            options={
                'verbose_name': 'Partida de Presupuesto',
                'verbose_name_plural': 'Partidas de Presupuesto',
                'ordering': ['budget', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItemMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_of_materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.billofmaterials')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.budgetitem')),
            ],
            options={
                'verbose_name': 'Material en Partida',
                'verbose_name_plural': 'Materiales en Partidas',
                'unique_together': {('budget_item', 'bill_of_materials')},
            },
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='materials',
            field=models.ManyToManyField(related_name='budget_items', through='core.BudgetItemMaterial', to='core.billofmaterials'),
        ),
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_version', models.PositiveIntegerField()),
                ('total_load_amps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('demand_load_amps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('conductor_catalog_id', models.UUIDField(blank=True, null=True)),
                ('breaker_catalog_id', models.UUIDField(blank=True, null=True)),
                ('voltage_drop_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_compliant', models.BooleanField(blank=True, null=True)),
                ('full_input_snapshot', models.JSONField(blank=True, null=True)),
                ('full_output_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculation_history', to=settings.AUTH_USER_MODEL)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_history', to='core.circuit')),
            ],
            options={
                'verbose_name': 'Historial de Cálculo',
                'verbose_name_plural': 'Históricos de Cálculo',
                'ordering': ['circuit', '-calculation_version'],
            },
        ),
        migrations.CreateModel(
            name='CalculationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('overcurrent', 'Sobrecorriente'), ('voltage_drop', 'Caída de Tensión'), ('short_circuit', 'Cortocircuito'), ('temperature', 'Temperatura')], max_length=20)),
                ('severity', models.CharField(choices=[('warning', 'Advertencia'), ('error', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('calculation_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.calculationhistory')),
            ],
            options={
                'verbose_name': 'Alerta de Cálculo',
                'verbose_name_plural': 'Alertas de Cálculo',
                'ordering': ['severity', 'alert_type'],
            },
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='circuit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_entries', to='core.circuit'),
        ),
        migrations.CreateModel(
            name='CircuitCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_version', models.PositiveIntegerField(default=1)),
                ('total_load_amps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('demand_load_amps', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('voltage_drop_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_compliant', models.BooleanField(blank=True, null=True)),
                ('parameters_snapshot', models.JSONField(blank=True, null=True)),
                ('calculation_date', models.DateTimeField(auto_now=True)),
                ('breaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_calculations', to='core.breakercatalog')),
                ('circuit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='core.circuit')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_calculations', to='core.conductorcatalog')),
            ],
            options={
                'verbose_name': 'Cálculo de Circuito',
                'verbose_name_plural': 'Cálculos de Circuitos',
            },
        ),
        migrations.CreateModel(
            name='ElectricalPanel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('main_breaker_ampacity', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('is_subpanel', models.BooleanField(default=False)),
                ('parent_panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_panels', to='core.electricalpanel')),
            ],
            options={
                'verbose_name': 'Tablero Eléctrico',
                'verbose_name_plural': 'Tableros Eléctricos',
                'ordering': ['project', 'name'],
            },
        ),
        migrations.AddField(
            model_name='circuit',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circuits', to='core.electricalpanel'),
        ),
        migrations.AddField(
            model_name='conductorcatalog',
            name='insulation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='catalog_entries', to='core.insulationtype'),
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('power_watts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voltage_v', models.DecimalField(decimal_places=1, default=120.0, max_digits=5)),
                ('power_factor', models.DecimalField(decimal_places=2, default=0.9, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(1.0)])),
                ('is_continuous', models.BooleanField(default=False)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='core.circuit')),
                ('load_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='loads', to='core.loadtype')),
            ],
            options={
                'verbose_name': 'Carga',
                'verbose_name_plural': 'Cargas',
                'ordering': ['circuit', 'name'],
            },
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bom_entries', to='core.materialcatalog'),
        ),
        migrations.AddField(
            model_name='materialcatalog',
            name='unit_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='materials', to='core.materialunitmeasure'),
        ),
        migrations.CreateModel(
            name='NormVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(max_length=50)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('norm', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='versions', to='core.norm')),
            ],
            options={
                'verbose_name': 'Versión de Norma',
                'verbose_name_plural': 'Versiones de Normas',
                'ordering': ['norm', '-effective_from'],
                'unique_together': {('norm', 'version_name')},
            },
        ),
        migrations.AddField(
            model_name='conductorcatalog',
            name='norm_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='conductors', to='core.normversion'),
        ),
        migrations.AddField(
            model_name='breakercatalog',
            name='norm_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='breakers', to='core.normversion'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['resource', 'action'],
                'unique_together': {('resource', 'action')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('calculated', 'Calculado'), ('budgeted', 'Presupuestado'), ('archived', 'Archivado')], default='draft', max_length=15)),
                ('norm_version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='core.normversion')),
                ('phase_config', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='core.phaseconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='electricalpanel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='core.project'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_version', models.PositiveIntegerField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('pdf_memory', 'Memoria de Cálculo PDF'), ('xlsx_budget', 'Presupuesto Excel'), ('svg_diagram', 'Diagrama Unifilar SVG'), ('pdf_full', 'Informe Completo PDF')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_url', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.project'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='core.project'),
        ),
        migrations.CreateModel(
            name='ProjectParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ambient_temp_c', models.DecimalField(decimal_places=1, default=30.0, max_digits=4)),
                ('altitude_m', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('max_voltage_drop_pct', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('safety_factor', models.DecimalField(decimal_places=2, default=1.25, max_digits=3)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='core.project')),
            ],
            options={
                'verbose_name': 'Parámetros del Proyecto',
                'verbose_name_plural': 'Parámetros de Proyectos',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.UUIDField()),
                ('action', models.CharField(choices=[('INSERT', 'Inserción'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('SOFT_DELETE', 'Eliminación lógica')], max_length=15)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='VoltageLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voltage_numeric', models.DecimalField(decimal_places=1, max_digits=6)),
                ('phase_type', models.CharField(choices=[('single', 'Monofásica'), ('split', 'Bifásica'), ('three', 'Trifásica')], max_length=10)),
                ('frequency', models.DecimalField(decimal_places=1, default=60.0, max_digits=4)),
            ],
            options={
                'verbose_name': 'Nivel de Tensión',
                'verbose_name_plural': 'Niveles de Tensión',
                'ordering': ['voltage_numeric'],
                'unique_together': {('voltage_numeric', 'phase_type', 'frequency')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='voltage_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='projects', to='core.voltagelevel'),
        ),
        migrations.AddField(
            model_name='conductorcatalog',
            name='wire_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='catalog_entries', to='core.wirematerial'),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.project')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['project', 'sort_order', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='electricalpanel',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='core.zone'),
        ),
        migrations.AlterUniqueTogether(
            name='circuit',
            unique_together={('panel', 'circuit_number')},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('project', 'version')},
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.role')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserTenantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignments', to='core.role')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de Usuario en Tenant',
                'verbose_name_plural': 'Roles de Usuarios en Tenants',
                'unique_together': {('user', 'tenant', 'role')},
            },
        ),
    ]
